// -----------------------------------------------------------------------------
// AUTO-GENERATED FILE.
//
// Generated by:
//   scripts/generate-tanstack-features.ts
//
// Source:
//   @tanstack/table-core stockFeatures
//
// DO NOT EDIT THIS FILE MANUALLY.
//
// Public DataTable feature names are defined in:
//   featureAliases.ts
//
// Intentionally unsupported TanStack features are defined in:
//   ignoredTanStackFeatures.ts
// -----------------------------------------------------------------------------

import {
  columnFilteringFeature,
  columnOrderingFeature,
  columnPinningFeature,
  columnResizingFeature,
  columnSizingFeature,
  columnVisibilityFeature,
  globalFilteringFeature,
  rowExpandingFeature,
  rowPaginationFeature,
  rowSelectionFeature,
  rowSortingFeature,
} from "@tanstack/table-core";


/**
 * Runtime mapping between DataTable's stable public feature
 * names and the corresponding TanStack feature slots.
 *
 * This map contains only features explicitly exposed by
 * DataTable.
 */
export const featureMap = {
  sorting: {
    slot: "rowSortingFeature",
    feature: rowSortingFeature,
  },

  filtering: {
    slot: "columnFilteringFeature",
    feature: columnFilteringFeature,
  },

  globalFiltering: {
    slot: "globalFilteringFeature",
    feature: globalFilteringFeature,
  },

  ordering: {
    slot: "columnOrderingFeature",
    feature: columnOrderingFeature,
  },

  pagination: {
    slot: "rowPaginationFeature",
    feature: rowPaginationFeature,
  },

  selection: {
    slot: "rowSelectionFeature",
    feature: rowSelectionFeature,
  },

  expanding: {
    slot: "rowExpandingFeature",
    feature: rowExpandingFeature,
  },

  visibility: {
    slot: "columnVisibilityFeature",
    feature: columnVisibilityFeature,
  },

  pinning: {
    slot: "columnPinningFeature",
    feature: columnPinningFeature,
  },

  sizing: {
    slot: "columnSizingFeature",
    feature: columnSizingFeature,
  },

  resizing: {
    slot: "columnResizingFeature",
    feature: columnResizingFeature,
  },
} as const;


/**
 * Exact generated feature map type.
 */
export type FeatureMap =
  typeof featureMap;
