"use client";

import { Box, TableCell } from "@mui/material";
import type { CellData, Header, RowData } from "@tanstack/table-core";
import type { MuiDataTableFeatures } from "../features";
import type { MuiDataTableInstance } from "../table";
import { resolveTableCellAlignment } from "./alignment";
import { getDataTablePinnedLayout, getDataTablePinnedSx } from "./pinning";
import { DataTableHeaderContent } from "./DataTableHeaderContent";
import { getDataTableDensityMetrics, useDataTableDensity } from "../density";

export interface DataTableHeaderCellProps<
  TData extends RowData,
  TValue extends CellData = CellData,
> {
  readonly table: MuiDataTableInstance<TData>;
  readonly header: Header<MuiDataTableFeatures, TData, TValue>;

  /**
   * Zero-based visual header row position.
   *
   * Used to calculate vertical sticky offsets.
   */
  readonly headerRowIndex: number;
}

/**
 * Renders a single MUI header cell.
 *
 * Rendering itself is delegated to TanStack's AppHeader/FlexRender
 * infrastructure.
 *
 * This means:
 *
 * - custom column header renderers work
 * - grouped headers work
 * - the correct HeaderContext is supplied
 * - future registered header components work
 */
export function DataTableHeaderCell<
  TData extends RowData,
  TValue extends CellData = CellData,
>(props: DataTableHeaderCellProps<TData, TValue>) {
  const { table, header, headerRowIndex } = props;

  const { density } = useDataTableDensity();

  const densityMetrics = getDataTableDensityMetrics(density);

  const stickyTop = headerRowIndex * densityMetrics.headerHeight;

  const meta = header.column.columnDef.meta;

  const align = resolveTableCellAlignment(meta?.headerAlign ?? meta?.align);

  const isLeafHeader = header.subHeaders.length === 0;

  /**
   * Placeholder headers are generated by TanStack when nested/grouped
   * columns require structural cells to keep header rows aligned.
   *
   * We still render the <TableCell>, but there is no content.
   */
  if (header.isPlaceholder) {
    return (
      <table.Subscribe
        // source={table.atoms.columnSizing}
        selector={(state) => ({
          columnSizing: state.columnSizing,
          columnVisibility: state.columnVisibility,
          columnPinning: state.columnPinning,
        })}
      >
        {() => {
          const size = header.getSize();

          const pinnedLayout = isLeafHeader
            ? getDataTablePinnedLayout(table, header.column)
            : undefined;

          const pinnedSx = getDataTablePinnedSx(pinnedLayout, "header");

          return (
            <TableCell
              align={align}
              colSpan={header.colSpan}
              data-column-id={header.column.id}
              data-pinned={pinnedLayout?.position}
              data-density={density}
              sx={{
                /**
                 * All header cells own vertical stickiness.
                 *
                 * Pinned leaf headers additionally receive logical
                 * inline positioning through pinnedSx.
                 */
                position: "sticky",
                top: `${stickyTop}px`,
                zIndex: 2,
                backgroundColor: "background.paper",
                boxSizing: "border-box",
                width: `${size}px`,
                minWidth: `${size}px`,
                maxWidth: `${size}px`,
                height: `${densityMetrics.headerHeight}px`,
                minHeight: `${densityMetrics.headerHeight}px`,
                px: densityMetrics.cellPaddingInline,
                py: densityMetrics.cellPaddingBlock,
                // whiteSpace: "nowrap",
                // overflow: "hidden",
                ...pinnedSx,
              }}
            />
          );
        }}
      </table.Subscribe>
    );
  }

  return (
    <table.AppHeader
      header={header}
      selector={(state) => ({
        columnSizing: state.columnSizing,
        columnResizing: state.columnResizing,
        columnVisibility: state.columnVisibility,
        columnPinning: state.columnPinning,
        sorting: state.sorting,
      })}
    >
      {(appHeader) => {
        /**
         * Calculate these values inside the subscribed render function.
         *
         * AppHeader may rerender independently of this outer React
         * component.
         */
        const size = header.getSize();

        const pinnedLayout = isLeafHeader
          ? getDataTablePinnedLayout(table, header.column)
          : undefined;

        const pinnedSx = getDataTablePinnedSx(pinnedLayout, "header");

        const sortDirection = isLeafHeader
          ? header.column.getIsSorted()
          : false;

        return (
          <TableCell
            align={align}
            colSpan={header.colSpan}
            scope="col"
            data-column-id={header.column.id}
            data-pinned={pinnedLayout?.position}
            data-density={density}
            sortDirection={sortDirection}
            sx={{
              /**
               * Vertically sticky for every header.
               *
               * Pinned leaf headers additionally receive logical
               * inline positioning through pinnedSx.
               */
              position: "sticky",
              top: `${stickyTop}px`,
              zIndex: 2,
              backgroundColor: "background.paper",
              boxSizing: "border-box",
              width: `${size}px`,
              minWidth: `${size}px`,
              maxWidth: `${size}px`,
              height: `${densityMetrics.headerHeight}px`,
              minHeight: `${densityMetrics.headerHeight}px`,
              px: densityMetrics.cellPaddingInline,
              py: densityMetrics.cellPaddingBlock,
              whiteSpace: densityMetrics.nowrap ? "nowrap" : "normal",
              overflow: "hidden",

              /**
               * Pinned leaf headers override the inline sticky position and
               * z-index while preserving the top offset above.
               */
              ...pinnedSx,
            }}
          >
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent:
                  align === "right"
                    ? "flex-end"
                    : align === "center"
                      ? "center"
                      : "flex-start",
                minWidth: 0,
                height: "100%",
                overflow: "hidden",
              }}
            >
              {/* <Box
                sx={{
                  minWidth: 0,
                  overflow: "hidden",
                  textOverflow: "ellipsis",
                }}
              >
                <appHeader.FlexRender />
              </Box> */}
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent:
                    align === "right"
                      ? "flex-end"
                      : align === "center"
                        ? "center"
                        : "flex-start",
                  minWidth: 0,
                  height: "100%",
                  overflow: "hidden",
                }}
              >
                <DataTableHeaderContent table={table} header={header} />
              </Box>
            </Box>
            {/**
             * Only leaf headers should expose a resize handle.
             *
             * A group header's getSize() is derived from its descendants,
             * so resizing the group itself would be ambiguous.
             */}
            {/* {header.subHeaders.length === 0 && <appHeader.ResizeHandle />} */}
            {isLeafHeader && <appHeader.ResizeHandle />}
          </TableCell>
        );
      }}
    </table.AppHeader>
  );
}
